src/app.py
from flask import Flask, render_template
from src.common.database import Database

__author__ = 'yuqian'


app = Flask(__name__)
app.config.from_object('src.config')
app.secret_key = "123"


@app.before_first_request
def init_db():
    Database.initialize()


@app.route('/')
def home():
    return render_template('home.jinja2')

from src.models.users.views import user_blueprint
from src.models.stores.views import store_blueprint
from src.models.alerts.views import alert_blueprint
app.register_blueprint(user_blueprint, url_prefix="/users")
app.register_blueprint(store_blueprint, url_prefix="/stores")
app.register_blueprint(alert_blueprint, url_prefix="/alerts")

src/models/alerts/views.py
from flask import Blueprint, request, render_template, session, redirect, url_for

from src.models.alerts.alert import Alert
from src.models.items.item import Item
import src.models.users.decorators as user_decorators



alert_blueprint = Blueprint('alerts', __name__)


@alert_blueprint.route('/new', methods=['GET', 'POST'])
@user_decorators.requires_login
def create_alert():
    if request.method == 'POST':
        name = request.form['name']
        url = request.form['url']
        price_limit = float(request.form['price_limit'])

        item = Item(name, url)
        item.save_to_mongo()

        alert = Alert(session['email'], price_limit, item._id)
        alert.load_item_price()  # This already saves to MongoDB

    # What happens if it's a GET request
    return render_template("alerts/new_alert.jinja2")  # Send the user an error if their login was invalid


@alert_blueprint.route('/edit/<string:alert_id>', methods=['GET', 'POST'])
@user_decorators.requires_login
def edit_alert(alert_id):
    if request.method == 'POST':
        price_limit = float(request.form['price_limit'])

        alert = Alert.find_by_id(alert_id)
        alert.price_limit = price_limit
        alert.load_item_price()  # This already saves to MongoDB

    # What happens if it's a GET request
    return render_template("alerts/edit_alert.jinja2", alert=Alert.find_by_id(alert_id))  # Send the user an error if their login was invalid


@alert_blueprint.route('/deactivate/<string:alert_id>')
@user_decorators.requires_login
def deactivate_alert(alert_id):
    Alert.find_by_id(alert_id).deactivate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/activate/<string:alert_id>')
@user_decorators.requires_login
def activate_alert(alert_id):
    Alert.find_by_id(alert_id).activate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/delete/<string:alert_id>')
@user_decorators.requires_login
def delete_alert(alert_id):
    Alert.find_by_id(alert_id).delete()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/<string:alert_id>')
@user_decorators.requires_login
def get_alert_page(alert_id):
    return render_template('alerts/alert.jinja2', alert=Alert.find_by_id(alert_id))


@alert_blueprint.route('/check_price/<string:alert_id>')
def check_alert_price(alert_id):
    Alert.find_by_id(alert_id).load_item_price()
    return redirect(url_for('.get_alert_page', alert_id=alert_id))

src/models/items/views.py
from flask import Blueprint


item_blueprint = Blueprint('items', __name__)


@item_blueprint.route('/item/<string:name>')
def item_page(name):
    pass

src/models/stores/views.py
import json

from flask import Blueprint, render_template, request, redirect, url_for

from src.models.stores.store import Store

store_blueprint = Blueprint('stores', __name__)


@store_blueprint.route('/')
def index():
    stores = Store.all()
    return render_template('stores/store_index.jinja2', stores=stores)


@store_blueprint.route('/new', methods=['GET', 'POST'])
def create_store():
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        Store(name, url_prefix, tag_name, query).save_to_mongo()

    # What happens if it's a GET request
    return render_template("stores/new_store.jinja2")


@store_blueprint.route('/edit/<string:store_id>', methods=['GET', 'POST'])
def edit_store(store_id):
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        store = Store.get_by_id(store_id)

        store.name = name
        store.url_prefix = url_prefix
        store.tag_name = tag_name
        store.query = query

        store.save_to_mongo()

        return redirect(url_for('.index'))

    # What happens if it's a GET request
    return render_template("stores/edit_store.jinja2", store=Store.get_by_id(store_id))


@store_blueprint.route('/delete/<string:store_id>')
def delete_store(store_id):
    Store.get_by_id(store_id).delete()


@store_blueprint.route('/<string:store_id>')
def store_page(store_id):
    return render_template('stores/store.jinja2', store=Store.get_by_id(store_id))

src/models/users/views.py
from flask import Blueprint, request, session, url_for, render_template
from werkzeug.utils import redirect
from src.models.users.user import User
import src.models.users.errors as UserErrors
import src.models.users.decorators as user_decorators

user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.is_login_valid(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/login.jinja2")  # Send the user an error if their login was invalid


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.register_user(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/register.jinja2")  # Send the user an error if their login was invalid


@user_blueprint.route('/alerts')
@user_decorators.requires_login
def user_alerts():
    user = User.find_by_email(session['email'])
    return render_template("users/alerts.jinja2", alerts=user.get_alerts())


@user_blueprint.route('/logout')
def logout_user():
    session['email'] = None
    return redirect(url_for('home'))


@user_blueprint.route('/check_alerts/<string:user_id>')
@user_decorators.requires_login
def check_user_alerts(user_id):
    pass

src/templates/alerts/alert.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Alert
            <small>for '{{ alert.item.name }}'</small>
        </h1>
    </div>
    <p>Last price found <strong>£{{ alert.item.price }}</strong></p>
    <p>Last checked on <strong>{{ alert.last_checked.strftime("%d-%m-%Y %H:%M") }}</strong></p>
    <div class="panel panel-default">
        <div class="panel-body">
            <a class="btn btn-default" href="{{ alert.item.url }}" role="button">Visit Site</a>
            <a class="btn btn-default" href="{{ url_for('alerts.edit_alert', alert_id=alert._id) }}" role="button">Edit Alert</a>
            {% if alert.active %}
                <a class="btn btn-danger" href="{{ url_for('alerts.deactivate_alert', alert_id=alert._id) }}" role="button">Deactivate Alert</a>
            {% else %}
                <a class="btn btn-success" href="{{ url_for('alerts.activate_alert', alert_id=alert._id) }}" role="button">Activate Alert</a>
                <a class="btn btn-danger" href="{{ url_for('alerts.delete_alert', alert_id=alert._id) }}" role="button">Permanently Delete Alert</a>
            {% endif %}
            <a class="btn btn-warning" href="{{ url_for('alerts.check_alert_price', alert_id=alert._id) }}" role="button">Check Price Now</a>
        </div>
    </div>
{% endblock %}

src/templates/alerts/edit_alert.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Edit Alert</h1>
    </div>
    <div class="form">
        <form method="post">
            <div class="form-group">
                <label for="name">Alert/Item Name</label>
                <input type="text" class="form-control" id="name" name="name" value="{{ alert.item.name }}" disabled>
            </div>
            <div class="form-group">
                <label for="url">Item URL</label>
                <input type="text" class="form-control" id="url" name="url" value="{{ alert.item.url }}" disabled>
            </div>
            <div class="form-group">
                <label for="price_limit">Alert limit</label>
                <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="45.0"
                       aria-describedby="priceLimitBlock" value="{{ alert.price_limit }}">
                <span id="priceLimitBlock" class="help-block">We'll send you an e-mail when the price reaches or goes under this.</span>
            </div>
            <button type="submit" class="btn btn-default">Update</button>
        </form>
    </div>
{% endblock %}

src/templates/alerts/new_alert.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Create Alert</h1>
    </div>
    <div class="form">
        <form method="post">
            <div class="form-group">
                <label for="name">Alert/Item Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Name">
            </div>
            <div class="form-group">
                <label for="url">Item URL</label>
                <input type="text" class="form-control" id="url" name="url" placeholder="http://...">
            </div>
            <div class="form-group">
                <label for="price_limit">Alert limit</label>
                <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="45.0"
                       aria-describedby="priceLimitBlock">
                <span id="priceLimitBlock" class="help-block">We'll send you an e-mail when the price reaches or goes under this.</span>
            </div>
            <button type="submit" class="btn btn-default">Create</button>
        </form>
    </div>
{% endblock %}

src/templates/base.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Price Alerts</title>

    {% include 'html_dependencies.jinja2' %}

</head>
<body>

<nav class="navbar navbar-fixed-top navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/" title="Home">Pricing</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('stores.index') }}" title="Stores">Stores</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if session['email'] %}
                    <li><a href="{{ url_for('users.user_alerts') }}" title="Your Alerts"><span class="glyphicon glyphicon-user"></span> Your Alerts</a></li>
                    <li><a href="{{ url_for('users.logout_user') }}" title="Log Out"><span class="glyphicon glyphicon-log-out"></span> Log out</a></li>
                {% else %}
                    <li><a href="{{ url_for('users.register_user') }}" title="Sign up"><span class="glyphicon glyphicon-user"></span> Sign up</a></li>
                    <li><a href="{{ url_for('users.login_user') }}" title="Log in"><span class="glyphicon glyphicon-log-in"></span> Log in</a></li>
                {% endif %}
            </ul>
            ​
        </div>
    </div>
</nav>

<div class="content container">
    {% block content %}

    {% endblock %}
</div>

</body>
</html>

src/templates/home.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="jumbotron">
        <h1>Pricing Service</h1>
        <p>We scan online store websites to alert you of price drops in items that interest you.</p>
        <p>Just sign up, and get started by adding the URL of an item that you wish to track. We'll do the rest!</p>
        <p><a class="btn btn-primary btn-lg" href="{{ url_for('users.register_user') }}" role="button">Get started</a></p>
    </div>
{% endblock %}

src/templates/html_dependencies.jinja2
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
<script src="http://code.jquery.com/jquery-2.2.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

src/templates/stores/edit_store.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Edit Store</h1>
    </div>
    <div class="form">
        <form method="post">
            <div class="form-group">
                <label for="name">Store name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Name" value="{{ store.name }}">
            </div>
            <div class="form-group">
                <label for="url_prefix">Store URL Prefix</label>
                <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="http://..."
                aria-describedby="storeURLPrefixHelp" value="{{ store.url_prefix }}">
                <span id="storeURLPrefixHelp" class="help-block">What characters do URLs of all items in this online store start with?</span>
            </div>
            <div class="form-group">
                <label for="tag_name">Tag name</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span"
                       aria-describedby="tagNameHelp" value="{{ store.tag_name }}">
                <span id="tagNameHelp" class="help-block">What is the HTML tag of the item that contains the item price? (usually 'span')</span>
            </div>
            <div class="form-group">
                <label for="query">Query</label>
                <input type="text" class="form-control" id="query" name="query" placeholder='{"id": "..."}'
                       aria-describedby="queryHelpBlock" value='{{ store.query | tojson }}'> <!-- If using double quotes here, it breaks! -->
                <span id="queryHelpBlock" class="help-block">What JSON query would we have to do to find the specific tag with the price?</span>
            </div>
            <button type="submit" class="btn btn-warning">Update</button>
        </form>
    </div>
{% endblock %}

src/templates/stores/new_store.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Create Store</h1>
    </div>
    <div class="form">
        <form method="post">
            <div class="form-group">
                <label for="name">Store name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Name">
            </div>
            <div class="form-group">
                <label for="url_prefix">Store URL Prefix</label>
                <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="http://..."
                aria-describedby="storeURLPrefixHelp">
                <span id="storeURLPrefixHelp" class="help-block">What characters do URLs of all items in this online store start with?</span>
            </div>
            <div class="form-group">
                <label for="tag_name">Tag name</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" value="span"
                       aria-describedby="tagNameHelp">
                <span id="tagNameHelp" class="help-block">What is the HTML tag of the item that contains the item price? (usually 'span')</span>
            </div>
            <div class="form-group">
                <label for="query">Query</label>
                <input type="text" class="form-control" id="query" name="query" placeholder='{"id": "..."}'
                       aria-describedby="queryHelpBlock">
                <span id="queryHelpBlock" class="help-block">What JSON query would we have to do to find the specific tag with the price?</span>
            </div>
            <button type="submit" class="btn btn-default">Create</button>
        </form>
    </div>
{% endblock %}

src/templates/stores/store.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Store
            <small>{{ store.name }}</small>
        </h1>
    </div>
    <p>All URLs in this store should start with <strong>{{ store.url_prefix }}</strong></p>
    {% if session['email'] in config.ADMINS %}
        <div class="panel panel-default">
            <div class="panel-body">
                <a class="btn btn-warning" href="{{ url_for('stores.edit_store', store_id=store._id) }}" role="button">Edit
                    Store</a>
                <a class="btn btn-danger" href="{{ url_for('stores.delete_store', store_id=store._id) }}" role="button">Permanently
                    Delete Store</a>
            </div>
        </div>
    {% endif %}
{% endblock %}

src/templates/stores/store_index.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Stores
            <small>list of stores supported</small>
        </h1>
    </div>
    <div class="list-group">
        {% for store in stores %}
            <a href="{{ url_for('stores.store_page', store_id=store._id) }}" class="list-group-item">
                <h4 class="list-group-item-heading">{{ store.name }}</h4>
                <p class="list-group-item-text">All URLs in this store should start with
                    <strong>{{ store.url_prefix }}</strong></p>
            </a>
        {% endfor %}
    </div>
    {% if session['email'] in config.ADMINS %}
        <a class="btn btn-success" href="{{ url_for('stores.create_store') }}"><span
                class="glyphicon glyphicon-plus"></span> Create new</a>
    {% endif %}
{% endblock %}

src/templates/users/alerts.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Alerts
            <small>showing already existing alerts</small>
        </h1>
    </div>
    <div class="list-group">
        {% for alert in alerts %}
            <a href="/alerts/{{ alert._id }}"
               class="list-group-item {{ 'list-group-item-warning' if not alert.active else '' }}">
                <h4 class="list-group-item-heading">
                    {{ "<span class='glyphicon glyphicon-remove-circle'></span> " if not alert.active else '' }}
                    Alert for {{ alert.item.name }}
                </h4>
                <p class="list-group-item-text">Last price found <strong>£{{ alert.item.price }}</strong><br/>Last
                    checked on <strong>{{ alert.last_checked.strftime("%d-%m-%Y %H:%M") }}</strong></p>
            </a>
        {% endfor %}
    </div>
    <a class="btn btn-success" href="{{ url_for('alerts.create_alert') }}"><span
            class="glyphicon glyphicon-plus"></span> Create new</a>
{% endblock %}

src/templates/users/login.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="form">
        <form action="{{ url_for('users.login_user') }}" method="post">
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email"
                       aria-describedby="emailHelpBlock">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" name="password" id="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-default">Log in</button>
        </form>
    </div>
{% endblock %}

src/templates/users/register.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="form">
        <form action="{{ url_for('users.register_user') }}" method="post">
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email"
                       aria-describedby="emailHelpBlock">
                <span id="emailHelpBlock" class="help-block">Be sure to enter a valid e-mail, as that's where we'll send alerts.</span>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" name="password" id="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-default">Sign up</button>
        </form>
    </div>
{% endblock %}